# Generated by Django 5.2.12 on 2026-03-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('target_branch', models.CharField(blank=True, max_length=64, null=True)),
                ('target_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(choices=[('verification', 'Verification'), ('rejection', 'Rejection'), ('monthly', 'Monthly'), ('nudge', 'Nudge'), ('milestone', 'Milestone'), ('broadcast', 'Broadcast')], default='verification', max_length=32)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
