# Generated by Django 5.2.12 on 2026-03-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('category', models.CharField(default='other', max_length=32)),
                ('photos', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('seen', 'Seen'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('seen_by_hod', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('student_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('org', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('file', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('seen', 'Seen'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('seen_by_hod', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('student_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.URLField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('seen', 'Seen'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('seen_by_hod', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SemesterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.PositiveSmallIntegerField()),
                ('subjects_json', models.JSONField(default=list)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('entry_method', models.CharField(choices=[('ocr', 'OCR'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['semester_number'],
            },
        ),
    ]
